apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data-pvc
  labels:
    app: data-pipeline
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
